from setuptools import setup, find_packages

setup(
    name='mental_health_detection',
    version='0.1.0',
    description='A project for detecting mental health conditions from textual data using deep learning models.',
    author='Your Name',
    author_email='your.email@example.com',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    install_requires=[
        'pandas==2.0.0',
        'numpy==1.24.3',
        'nltk==3.8.1',
        'transformers==4.30.2',
        'scikit-learn==1.2.2',
        'gensim==4.3.1',
        'tensorflow==2.13.0',
        'tensorflow-gpu==2.13.0',
        'torch==2.0.1',
        'torchvision==0.15.2',
        'keras==2.13.1',
        'matplotlib==3.7.1',
        'seaborn==0.12.2',
        'plotly==5.15.0',
        'tqdm==4.65.0',
        'jupyter==1.0.0',
        'ipykernel==6.23.3',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.7',
)